version: '2.1'
orbs:
  gradle: circleci/gradle@x.y
workflows:
  checkout-build-test:
    jobs:
      - gradle/test:
          store_artifacts: build/reports/
          test_command: myTests
          test_results_path: build/test-results/